csrf:
  ssl_strict: false
  time_limit: 3600

database:
  track_modifications: False
  uri: platform.db

session:
  cookie:
    httponly: true
    samesite: Lax
    secure: false
  lifetime_days: 7

logging:
  level: INFO

# AI 代码上传目录
AI_CODE_UPLOAD_FOLDER: uploads/


# AI代码配置
ai:
  allowed_extensions: # 允许的文件扩展名
    - .py

# 初始用户配置
INITIAL_USERS:
  # admin 用户
  - username: admin
    email: admin@avalon.com
    password: Tuavalon
    is_admin: True
    ai_code:
      name: Admin Console
      description: 管理员控制台
      file_path: game/smart_player.py
      make_active: false
  # Smart AI 用户系列
  - username: smart_user1
    email: smart1@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user2
    email: smart2@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user3
    email: smart3@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user4
    email: smart4@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user5
    email: smart5@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user6
    email: smart6@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user7
    email: smart7@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
      
  # Basic AI 用户系列
  - username: basic_user1
    email: basic1@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user2
    email: basic2@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user3
    email: basic3@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user4
    email: basic4@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user5
    email: basic5@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user6
    email: basic6@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true

  # Idiot AI 用户系列
  - username: idiot_user1
    email: idiot1@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/idiot_player.py
      make_active: true
  - username: idiot_user2
    email: idiot2@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/idiot_player.py
      make_active: true
  - username: idiot_user3
    email: idiot3@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/idiot_player.py
      make_active: true
  - username: idiot_user4
    email: idiot4@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/idiot_player.py
      make_active: true
  - username: idiot_user5
    email: idiot5@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/idiot_player.py
      make_active: true
  - username: idiot_user6
    email: idiot6@example.com
    password: password123
    is_admin: False
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/idiot_player.py
      make_active: true